In [1]:
import torch

In [3]:
a = torch.tensor([1, 2, 3], dtype=torch.float,  requires_grad= True)
print(a)

tensor([1., 2., 3.], requires_grad=True)


In [10]:
print(a.grad)
out = a.sigmoid()
print(out)

None
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)


In [11]:
b = out.detach()
print(b)

tensor([0.7311, 0.8808, 0.9526])


In [13]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = x**2+y
z.backward()
print(z, x.grad, y.grad)
print(z.detach())


tensor(3., grad_fn=<AddBackward0>) tensor(2.) tensor(1.)
tensor(3.)
