In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
# introduction to tensor
# creating tensor scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim


0

In [14]:
scalar.item()

7

In [18]:
# tensor vector
vector = torch.tensor([7, 1])
vector

tensor([7, 1])

In [19]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

In [22]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [23]:
matrix.ndim

2

In [24]:
matrix.shape

torch.Size([2, 2])

In [27]:
# create random tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0106, 0.5399, 0.0739, 0.2794],
         [0.0063, 0.2080, 0.7323, 0.4843],
         [0.2352, 0.0174, 0.6893, 0.9791]]),
 torch.float32)

In [28]:
# create random tensor in image shape
random_img_tensor = torch.rand(size=(224, 224, 3))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [30]:
# zeros and ones tensor
zero_tensor = torch.zeros(size = (3, 3))
one_tensor = torch.ones(size = (2, 2, 2))

In [31]:
zero_tensor, one_tensor

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [35]:
# range tensor
zero_to_11_tensor_deprecated = torch.range(0, 12)
zero_to_11_tensor_deprecated

/tmp/ipykernel_13807/2438499062.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_11_tensor_deprecated = torch.range(0, 12)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [37]:
zero_to_11_tensor = torch.arange(0, 12)
zero_to_11_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
# crate a tensor of zeros with same shape to zero_to_11_tensor
ten_zeros = torch.zeros_like(input=zero_to_11_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
tensor_A = torch.arange(1, 7, dtype=torch.float32)
tensor_A

tensor([1., 2., 3., 4., 5., 6.])

In [46]:
tensor_A = tensor_A.reshape([3, 2])

In [48]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [61]:
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)

In [64]:
# matrix multiplication 
# Be aware of tensor dimensions !
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [76]:
# linear layer
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x) 
print(f'Input shape: {x.shape}\n')
print(f'Output: \n {output}\n Output shape: {output.shape}')

Input shape: torch.Size([3, 2])

Output: 
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([3, 6])


In [78]:
# Finding the min, max, mean, sum
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [82]:
print(f'Maximum: {x.max()}')
print(f'Minimum: {x.min()}')
print(f'Average: {x.type(torch.float32).mean()}') # without conversion there will be an error why ? 
print(f'Sum: {x.sum()}')    

Maximum: 90
Minimum: 0
Average: 45.0
Sum: 450


In [84]:
# positional max/min 
print(f'Minimum position: {x.argmin()}')
print(f'Maximum position: {x.argmax()}')

Minimum position: 0
Maximum position: 9


In [88]:
# reshape tensor
x.reshape([2, 5])

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [91]:
# view of a tensor
z = x.view(5, 2)

In [93]:
# change view of a tensor also change its original tensor
z[:, 0] = 5

In [98]:
z, x

(tensor([[ 5, 10],
         [ 5, 30],
         [ 5, 50],
         [ 5, 70],
         [ 5, 90]]),
 tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]))

In [104]:
x_stacked = torch.stack([x, x, x])
x, x_stacked

(tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]),
 tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90],
         [ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90],
         [ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]]))

In [107]:
x_reshape = x.reshape([1, 10])

In [109]:
print(f"Before squeeze: {x_reshape}, shape: {x_reshape.shape}")

Before squeeze: tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]]), shape: torch.Size([1, 10])


In [112]:
x_squeezed = x_reshape.squeeze()
print(f"After squeezed: {x_squeezed}, shape: {x_squeezed.shape}")

After squeezed: tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]), shape: torch.Size([10])


In [114]:
# unsqueezed 
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"After unsqueezed: {x_unsqueezed}, shape: {x_unsqueezed.shape}")

After unsqueezed: tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]]), shape: torch.Size([1, 10])


In [117]:
# permute : rearranges the dimensions of the tensor according to the specified order.
# Create tensor with specific shape
x_original = torch.rand([224, 224, 3])
# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [118]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [119]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [120]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [121]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [122]:
x[0, 0, :]

tensor([1, 2, 3])

In [123]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [127]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Randomness

In [125]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2012, 0.1478, 0.3702, 0.1441],
        [0.1284, 0.2582, 0.7732, 0.1060],
        [0.6737, 0.3027, 0.9716, 0.3592]])

Tensor B:
tensor([[0.6261, 0.9557, 0.0057, 0.6767],
        [0.2114, 0.3975, 0.4007, 0.9157],
        [0.0821, 0.8882, 0.4257, 0.2228]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [128]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])